// DCC Formula Lab
// PRIVATE diagnostic utility for testing candidate component weights.
// It must not be used as a published ranking until a formula is explicitly approved/versioned.
export const FORMULA_LAB_VERSION='formula-lab-v1';
const COMPONENTS=['verifiedProduction','lineupMarketCore','marketDepth','replacementAdvantage'];
const round=(v,n=4)=>{const p=10**n;return Math.round((Number(v||0)+Number.EPSILON)*p)/p;};
function percentileRank(values,value){const sorted=[...values].sort((a,b)=>a-b);if(sorted.length<=1)return 1;const below=sorted.filter(v=>v<value).length;const equal=sorted.filter(v=>v===value).length;return round((below+(equal-1)/2)/(sorted.length-1));}
function normalizeMatrix(matrix){const values={};for(const c of COMPONENTS)values[c]=(matrix.teams||[]).map(t=>Number(t[c])).filter(Number.isFinite);return(matrix.teams||[]).map(t=>({rosterId:t.rosterId,team:t.team,components:Object.fromEntries(COMPONENTS.map(c=>[c,Number.isFinite(Number(t[c]))?percentileRank(values[c],Number(t[c])):null]))}));}
export function runFormulaLab({matrix,candidates=[]}={}){if(matrix?.status!=='ready')return{status:'withheld',published:false,results:[]};const normalized=normalizeMatrix(matrix);const results=candidates.map(candidate=>{const weights={};let total=0;for(const c of COMPONENTS){const w=Math.max(0,Number(candidate?.weights?.[c]||0));weights[c]=w;total+=w;}if(total<=0)return{name:candidate?.name||'unnamed',status:'invalid-weights'};for(const c of COMPONENTS)weights[c]=weights[c]/total;const teams=normalized.map(t=>{let weighted=0,used=0;for(const c of COMPONENTS){const v=t.components[c];if(v==null)continue;weighted+=v*weights[c];used+=weights[c];}return{rosterId:t.rosterId,team:t.team,diagnosticScore:used?round(weighted/used):null,components:t.components};}).sort((a,b)=>(Number(b.diagnosticScore)||-1)-(Number(a.diagnosticScore)||-1)||String(a.rosterId).localeCompare(String(b.rosterId)));return{name:candidate?.name||'unnamed',status:'diagnostic-only',weights,teams:teams.map((t,i)=>({...t,diagnosticOrder:i+1}))};});return{status:'ready',published:false,formulaVersion:FORMULA_LAB_VERSION,results,interpretation:{purpose:'Compare how candidate weight systems behave before any DCC roster-strength formula is approved.',warning:'Diagnostic scores/orders are internal sensitivity outputs, not DCC rankings.'},provenance:{componentNormalization:'within-league empirical percentile rank',aiSelectedWeights:false,publishedRanking:false}};}
